---
version: '2'
services:
  alertmanager-conf:
    image: camptocamp/prometheus-alertmanager-conf:20170321-1
    environment:
      HIPCHAT_ROOM_ID: ${HIPCHAT_ROOM_ID}
      HIPCHAT_AUTH_TOKEN: ${HIPCHAT_AUTH_TOKEN}
      HIPCHAT_URL: ${HIPCHAT_URL}
    labels:
      io.rancher.container.start_once: 'true'
  alertmanager:
    image: prom/alertmanager:v0.6.2
    command:
    - -config.file=/etc/alertmanager/alertmanager.yml
    - -log.format=logger:stdout?json=true
    - -log.level=debug
    labels:
      io.rancher.scheduler.affinity:host_label: monitoring=true
      io.rancher.sidekicks: alertmanager-conf
    volumes:
    - alertmanager_puppetdb:/alertmanager
    volumes_from:
    - alertmanager-conf
  prometheus-auth-conf:
    image: camptocamp/prometheus-auth-conf:v0.1.3
    environment:
      GRAFANA_URL: ${GRAFANA_URL}
      PASSWORD: ${PROMETHEUS_PASSWORD}
      RESOLVER: 169.254.169.250
      USERNAME: ${PROMETHEUS_USERNAME}
    volumes:
    - /entrypoint
    - /etc/haproxy
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:host_label: monitoring=true
  prometheus-auth:
    image: haproxy:1.6-alpine
    entrypoint:
    - /entrypoint/run.sh
    volumes_from:
    - prometheus-auth-conf
    labels:
      io.rancher.scheduler.affinity:host_label: monitoring=true
      io.rancher.sidekicks: prometheus-auth-conf
    links:
    - prometheus-server:prometheus-server
  prometheus-config-merger:
    image: camptocamp/prometheus-config-merger:0.1.0
    environment:
      PROMETHEUS_SERVER_HOSTNAME: prometheus-server
    volumes:
    - metrics_conf_puppet:/etc/prometheus
    labels:
      io.rancher.scheduler.affinity:host_label: monitoring=true
  prometheus-server-conf:
    image: camptocamp/prometheus-server-conf:20170504-1
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:host_label: monitoring=true
    volumes:
    - metrics_conf_puppet:/etc/prometheus
  prometheus-server-rules-conf:
    image: camptocamp/prometheus-server-rules-conf:20170510-1
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:host_label: monitoring=true
    volumes:
    - metrics_conf_puppet:/etc/prometheus
  prometheus-server:
    image: prom/prometheus:v1.5.2
    command:
    - -config.file=/etc/prometheus/prometheus.yml
    - -storage.local.path=/prometheus
    - -storage.local.max-chunks-to-persist=131072
    - -storage.local.memory-chunks=262144
    - -log.format=logger:stdout?json=true
    - -alertmanager.url=http://alertmanager:9093
    volumes:
    - metrics_conf_puppet:/etc/prometheus
    - metrics_tsdb_puppet:/prometheus
    labels:
      io.rancher.scheduler.affinity:host_label: monitoring=true
      prometheus_port: '9090'
  prometheus:
    image: rancher/lb-service-haproxy:v0.5.9
    ports:
    - ${PROMETHEUS_PORT}:${PROMETHEUS_PORT}/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.affinity:host_label: monitoring=true
    links:
    - prometheus-auth:prometheus-auth
  prometheus-puppetdb-targets-conf:
    image: camptocamp/prometheus-puppetdb:0.5.1
    environment:
      PROMETHEUS_PUPPETDB_URL: http://puppetdb.puppet:8080
      PROMETHEUS_PUPPETDB_QUERY: ${PROMETHEUS_PUPPETDB_QUERY}
    volumes:
    - metrics_conf_puppet:/etc/prometheus
    labels:
      io.rancher.scheduler.affinity:host_label: monitoring=true
