---
version: '2'
services:
  prometheus-config-merger:
    image: camptocamp/prometheus-config-merger:0.2.0
    environment:
      PROMETHEUS_SERVER_HOSTNAME: prometheus-server
    volumes:
    - metrics_conf_puppet:/etc/prometheus
    labels:
      io.rancher.scheduler.affinity:host_label: monitoring=true
  prometheus-server-conf:
    image: camptocamp/prometheus-server-conf:20170828-1
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:host_label: monitoring=true
    volumes:
    - metrics_conf_puppet:/etc/prometheus
  prometheus-server-rules-conf:
    image: camptocamp/prometheus-server-rules-conf:20180213-1
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:host_label: monitoring=true
    volumes:
    - metrics_conf_puppet:/etc/prometheus
  prometheus-server:
    image: prom/prometheus:v2.1.0
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    - --web.enable-lifecycle
    volumes:
    - metrics_conf_puppet:/etc/prometheus
    - metrics_tsdb_puppet:/prometheus
    volumes_from:
    - prometheus-server-rules-conf
    labels:
      io.rancher.scheduler.affinity:host_label: monitoring=true
      io.rancher.sidekicks: prometheus-server-conf, prometheus-server-rules-conf, prometheus-config-merger, prometheus-puppetdb-targets-conf
      prometheus_port: '9090'
  prometheus:
    image: rancher/lb-service-haproxy:v0.7.15
    ports:
    - ${PROMETHEUS_PORT}:${PROMETHEUS_PORT}/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.affinity:host_label: monitoring=true
  prometheus-puppetdb-targets-conf:
    image: camptocamp/prometheus-puppetdb:0.5.2
    environment:
      PROMETHEUS_PUPPETDB_URL: http://puppetdb.puppet:8080
      PROMETHEUS_PUPPETDB_QUERY: ${PROMETHEUS_PUPPETDB_QUERY}
    volumes:
    - metrics_conf_puppet:/etc/prometheus
    labels:
      io.rancher.scheduler.affinity:host_label: monitoring=true
