---
version: '2'
services:
  prometheus-config-merger:
    image: camptocamp/prometheus-config-merger:0.2.0
    environment:
      PROMETHEUS_SERVER_HOSTNAME: prometheus-server
    volumes:
    - metrics_conf_puppet:/etc/prometheus
    labels:
      io.rancher.scheduler.affinity:host_label: monitoring=true
  prometheus-server-conf:
    image: camptocamp/prometheus-server-conf:20170828-1
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:host_label: monitoring=true
    volumes:
    - metrics_conf_puppet:/etc/prometheus
  prometheus-server-rules-conf:
    image: camptocamp/prometheus-custom-rules:r-metrics-20190618-1
    user: root
    command:
    - metrics
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:host_label: monitoring=true
    volumes:
    - metrics_conf_puppet:/etc/prometheus
  prometheus-server:
    image: prom/prometheus:v2.7.1
    command: '--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --web.enable-lifecycle --web.enable-admin-api ${PROMETHEUS_EXTRA_PARAMS} --log.format=json'
    volumes:
    - metrics_conf_puppet:/etc/prometheus
    - metrics_tsdb_puppet:/prometheus
    - prometheus-puppetdb-targets:/etc/prometheus-puppetdb
    volumes_from:
    - prometheus-server-rules-conf
    labels:
      io.rancher.scheduler.affinity:host_label: monitoring=true
      io.rancher.sidekicks: prometheus-server-conf, prometheus-server-rules-conf, prometheus-config-merger, prometheus-puppetdb, prometheus-puppetdb-server-conf
      prometheus_port: '9090'
      ssh_tunnel.port: '9090'
  prometheus:
    image: rancher/lb-service-haproxy:v0.9.11
    ports:
    - ${PROMETHEUS_PORT}:${PROMETHEUS_PORT}/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: monitoring=true
      ssh_tunnel.port: '8008'
  prometheus-puppetdb:
    image: camptocamp/prometheus-puppetdb:0.9.1
    environment:
      PROMETHEUS_PUPPETDB_OUTPUT: file
      PROMETHEUS_PUPPETDB_FILE: /etc/prometheus-puppetdb/targets.yml
      PROMETHEUS_PUPPETDB_URL: http://puppetdb.puppet:8080
    volumes:
    - prometheus-puppetdb-targets:/etc/prometheus-puppetdb
    labels:
      io.rancher.scheduler.affinity:host_label: monitoring=true
  prometheus-puppetdb-server-conf:
    image: camptocamp/prometheus-puppetdb-server-conf:20180507-2
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:host_label: monitoring=true
    volumes:
    - metrics_conf_puppet:/etc/prometheus
