version: '2'
services:
  prometheus:
    image: camptocamp/prometheus-server:v1.1.3
    volumes:
      - /etc/prometheus-config
  prometheus-puppet:
    image: camptocamp/prometheus-puppetdb:latest
    volumes_from:
      - prometheus
    external_links:
      - ${PUPPETDB_SERVICE}:puppetdb
