---
version: '2'
volumes:
  metrics_tsdb_puppet:
    external: true
    driver: 'null'
services:
  prometheus-auth-conf:
    image: camptocamp/prometheus-auth-conf:v0.1.3
    environment:
      GRAFANA_URL: ${GRAFANA_URL}
      PASSWORD: ${PROMETHEUS_PASSWORD}
      RESOLVER: 169.254.169.250
      USERNAME: ${PROMETHEUS_USERNAME}
    volumes:
    - /entrypoint
    - /etc/haproxy
    labels:
      io.rancher.container.start_once: 'true'
  prometheus-auth:
    image: haproxy:1.6-alpine
    entrypoint:
    - /entrypoint/run.sh
    volumes_from:
    - prometheus-auth-conf
    labels:
      io.rancher.scheduler.affinity:host_label: monitoring=true
      io.rancher.sidekicks: prometheus-auth-conf
  prometheus-server:
    image: camptocamp/prometheus-server:v1.1.3
    volumes:
    - metrics_tsdb_puppet:/prometheus
    volumes_from:
    - prometheus-server-conf
    labels:
      io.rancher.scheduler.affinity:host_label: monitoring=true
      io.rancher.sidekicks: prometheus-server-conf
  prometheus:
    image: rancher/lb-service-haproxy:v0.4.6
    ports:
    - ${PROMETHEUS_PORT}:${PROMETHEUS_PORT}/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.affinity:host_label: monitoring=true
  prometheus-server-conf:
    image: camptocamp/prometheus-puppetdb:0.3.0
    environment:
      PROMETHEUS_PUPPETDB_URL: http://puppetdb.puppet:8080
