---
version: '2'
volumes:
  metrics_tsdb_puppet: {}
services:
  prometheus-auth-conf:
    image: camptocamp/prometheus-auth-conf:v0.1.3
    environment:
      GRAFANA_URL: ${GRAFANA_URL}
      PASSWORD: ${PROMETHEUS_PASSWORD}
      RESOLVER: 169.254.169.250
      USERNAME: ${PROMETHEUS_USERNAME}
    volumes:
    - /entrypoint
    - /etc/haproxy
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:host_label: monitoring=true
  prometheus-auth:
    image: haproxy:1.6-alpine
    entrypoint:
    - /entrypoint/run.sh
    volumes_from:
    - prometheus-auth-conf
    labels:
      io.rancher.scheduler.affinity:host_label: monitoring=true
      io.rancher.sidekicks: prometheus-auth-conf
  prometheus-server-conf:
    image: camptocamp/prometheus-server-conf:latest
  prometheus-server:
    image: prom/prometheus:v1.5.2
    command:
    - -config.file=/etc/prometheus-config/prometheus.yml
    - -storage.local.path=/prometheus
    - -storage.local.max-chunks-to-persist=131072
    - -storage.local.memory-chunks=262144
    - -log.format=logger:stdout?json=true
    volumes:
    - metrics_prom_targets_puppet:/etc/prometheus-targets
    - metrics_tsdb_puppet:/prometheus
    volumes_from:
    - prometheus-server-conf
    labels:
      io.rancher.scheduler.affinity:host_label: monitoring=true
      io.rancher.sidekicks: prometheus-server-conf
      prometheus_port: '9090'
  prometheus:
    image: rancher/lb-service-haproxy:v0.5.9
    ports:
    - ${PROMETHEUS_PORT}:${PROMETHEUS_PORT}/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.affinity:host_label: monitoring=true
    links:
    - prometheus-auth:prometheus-auth
  prometheus-puppetdb-targets-conf:
    image: camptocamp/prometheus-puppetdb:0.4.3
    environment:
      PROMETHEUS_PUPPETDB_URL: http://puppetdb.puppet:8080
    volumes:
    - metrics_prom_targets_puppet:/etc/prometheus-targets
    labels:
      io.rancher.scheduler.affinity:host_label: monitoring=true
