---
version: '2'
.catalog:
  name: "Prometheus-PuppetDB"
  version: "v19"
  description: "Prometheus-PuppetDB"
  uuid: prometheus-puppetdb-19
  minimum_rancher_version: v1.2.0
  questions:
    - variable: "SSL_CERTIFICATE"
      label: "SSL Certificate"
      description: "A valid certificate from Rancher's infrastructure. Consider using Letsencrypt from the community catalog if you don't have any. The CN must match the 'Prometheus FQDN' below."
      type: "certificate"
      required: true
    - variable: "PROMETHEUS_PUPPETDB_QUERY"
      label: "PuppetDB query"
      description: "The PuppetDB PQL query to use to generate target list."
      type: "string"
      required: true
      default: "facts { name='ipaddress' and nodes { deactivated is null and ! (facts { name = 'osfamily' and value = 'RedHat' } and facts { name='operatingsystemmajrelease' and value = '5' }) and facts { name='collectd_version' and value ~ '^5\\\\.7' } and resources { type='Class' and title='Collectd' } } }"
    - variable: "PROMETHEUS_USERNAME"
      label: "Prometheus username"
      description: "Credentials used to access the prometheus API endpoint over HTTP."
      type: "string"
      default: "prometheus"
      required: true
    - variable: "PROMETHEUS_PASSWORD"
      label: "Prometheus password"
      description: "See Prometheus username"
      type: "password"
      required: true
    - variable: "PROMETHEUS_FQDN"
      label: "Prometheus FQDN. Must match the CN from the 'SSL Certificate' above."
      description: "The public FQDN (or IP address) where prometheus can be reached. Leave blank if you don't want this instance to be part of the central federation system."
      type: "string"
      required: false
    - variable: "PROMETHEUS_PORT"
      label: "Prometheus port"
      description: "The port used to access prometheus."
      type: "string"
      default: "9443"
      required: true
    - variable: "PROMETHEUS_SCHEME"
      label: "Prometheus scheme"
      description: "Don't change the default unless you know what you're doing."
      type: "enum"
      options:
        - "https"
        - "http"
      default: "https"
    - variable: "GRAFANA_URL"
      label: "Grafana URL"
      description: "URL of Grafana instance, which will be added to outgoing CORS headers."
      type: "string"
      default: "https://grafana.camptocamp.com"
      required: true
    - variable: HIPCHAT_ROOM_ID
      label: HipChat Room ID
      description: The HipChat Room ID.
      type: int
    - variable: HIPCHAT_AUTH_TOKEN
      label: The HipChat auth token.
      type: string
    - variable: HIPCHAT_URL
      label: The HipChat URL to send API requests to.
      type: string
services:
  prometheus:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      default_cert: ${SSL_CERTIFICATE}
      port_rules:
      - priority: 1
        protocol: ${PROMETHEUS_SCHEME}
        service: prometheus-auth
        source_port: ${PROMETHEUS_PORT}
        target_port: 8080
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
