---
version: '2'
.catalog:
  name: "Prometheus-PuppetDB"
  version: v40
  description: "Prometheus-PuppetDB"
  minimum_rancher_version: v1.2.0
  questions:
    - variable: "SSL_CERTIFICATE"
      label: "SSL Certificate"
      description: "A valid certificate from Rancher's infrastructure. Consider using Letsencrypt from the community catalog if you don't have any."
      type: "certificate"
      required: true
    - variable: "PROMETHEUS_USERNAME"
      label: "Prometheus username"
      description: "Credentials used to access the prometheus API endpoint over HTTP."
      type: "string"
      default: "prometheus"
      required: true
    - variable: "PROMETHEUS_PASSWORD"
      label: "Prometheus password"
      description: "See Prometheus username"
      type: "password"
      required: true
    - variable: "PROMETHEUS_PORT"
      label: "Prometheus port"
      description: "The port used to access prometheus."
      type: "string"
      default: "9443"
      required: true
    - variable: "PROMETHEUS_SCHEME"
      label: "Prometheus scheme"
      description: "Don't change the default unless you know what you're doing."
      type: "enum"
      options:
        - "https"
        - "http"
      default: "https"
    - variable: "PROMETHEUS_EXTRA_PARAMS"
      label: "Prometheus custom parameters"
      description: "Non-default prometheus command-line parameters"
      type: "string"
      default: ""
      required: false

services:
  prometheus:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      config: |-
        global
            log /var/lib/haproxy/dev/log local2 debug
            log /dev/log                 local2 debug
            stats socket /run/haproxy/admin.sock mode 660 level admin

        defaults
            log       global
            mode      http
            option    httplog
            log-tag   haproxy-promssl

        listen stats
            bind *:8008
            stats enable
            stats uri /stats

        userlist prometheus
            group prometheus
            user ${PROMETHEUS_USERNAME} insecure-password ${PROMETHEUS_PASSWORD} groups prometheus

        backend ${PROMETHEUS_PORT}_
            acl valid_user http_auth(prometheus)
            http-request auth realm Prometheus if !valid_user
            http-request deny if METH_POST { path_beg /-/ }
            http-request deny if { path_beg /api/v2/admin }
            http-request deny if METH_DELETE
            rspadd Access-Control-Allow-Origin:\ *
            rspadd Access-Control-Allow-Credentials:\ true
      default_cert: ${SSL_CERTIFICATE}
      port_rules:
      - priority: 1
        protocol: ${PROMETHEUS_SCHEME}
        service: prometheus-server
        source_port: ${PROMETHEUS_PORT}
        target_port: 9090
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
  prometheus-server:
    scale: 1
    start_on_create: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 9090
      unhealthy_threshold: 3
      initializing_timeout: 300000
      interval: 2000
      strategy: none
      request_line: GET "/-/healthy" "HTTP/1.0"
      reinitializing_timeout: 300000
