---
version: '2'
.catalog:
  name: "Prometheus-PuppetDB"
  version: "v0.1.0-1"
  description: "Prometheus-PuppetDB"
  uuid: prometheus-puppetdb-0
  minimum_rancher_version: v1.2.0
  questions:
    - variable: "PUPPETDB_SERVICE"
      label: "PuppetDB"
      description: "PuppetDB Service"
      type: "service"
      default: "puppet/puppetdb"
      required: true
